trigger:
  branches:
    include:
      - main

parameters:
  - name: env
    displayName: Select Deployment Environment
    default: dev
    type: string
    values:
      - dev
      - tst
      - acc
      - prd
variables:
  - template: ${{variables['System.DefaultWorkingDirectory']}}/azure-pipeline/variables/common.yaml
  - template: ${{variables['System.DefaultWorkingDirectory']}}/azure-pipeline/variables/${{ parameters.env }}.yaml
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/src/python-sample-vscode-flask-tutorial-main/Dockerfile'

stages:
- stage: Build
  displayName: 'Build and Push'
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        containerRegistry: ${{ variables.dockerRegsitrySC }}
        repository: ${{ variables.acrName }}
        command: build
        dockerfile: $(dockerfilePath)
        tags: ${{ variables.imageTag }}

    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        containerRegistry: ${{ variables.dockerRegsitrySC }}
        repository: ${{ variables.acrName }}
        command: push
        tags: ${{ variables.imageTag }}
